### ISSUE TITLE
Footer is not displayed anymore with recent Chromiums

### ISSUE THREAD

**Issue by maltoe** [bitcrowd/chromic_pdf#290]
Footer templates set via `ChromicPDF.Template` are not displayed anymore with recent Chromiums.

`ChromicPDF.Template` sets page dimensions and header/footer dimensions via rules in `@page { ... }` and sets `preferCSSPageSize: true` in the `printToPDF` call. Some time after Chromium 117, footers set via `footerTemplate` have disappeared (margin is there but blank).

## Analysis so far

- Somewhere in between Chromium 117.0.5938.62 and 119.0.6045.159
- setting the page margins via `printToPDF` options (in inches) fixes it
- but even if only `margin-top` is present in `@page`, it breaks again
  - even with `preferCSSPageSize: false`

## Minified example of what is broken

```css
@page {
  size: 210mm 297mm;
  /* or any other variation of specifying margin-top and margin-bottom */
  margin: 40mm 0 40mm;
}
```

See [stylesheet](https://github.com/bitcrowd/chromic_pdf/blob/ed525c2400922cc83ebdd41eaa8907de68cb0c55/lib/chromic_pdf/template.ex#L245-L275) for actual code.

## Things we've tried

- `size` vs. `width/height` in `@page` has no effect
- removing the `zoom` rule from `#header, #footer` has no effect
- keeping a `margin-inline: ...` is ok, but specifying top/bottom in the CSS immediately breaks it
